services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: db
    extra_hosts:
      - localhost:host-gateway
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pw
      POSTGRES_USER: user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 3s

  flyway-migrate:
    image: flyway/flyway
    container_name: flyway-migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/db
    command: -user=user -password=pw -cleanDisabled=false clean migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  mermerd:
    image: alpine:3.17.3
    extra_hosts:
      - localhost:host-gateway
    container_name: mermerd
    volumes:
      - ./:/app/
#    working_dir: /app/
#    command:
#      - sh
#      - -c
#      - |
#        apk add libc6-compat
#        ./mermerd --runConfig mermerdConfig.yaml -o this-erdiagram.mmd --debug
#        chown $MY_UID:$MY_GID this-erdiagram.mmd
    working_dir: /mermerd/
    command:
      - sh
      - -c
      - |
        apk add libc6-compat
        tar -xf mermerd_0.7.0_linux_amd64.tar.gz
        ./mermerd --runConfig /app/mermerdConfig.yaml -o /app/this-erdiagram.mmd --debug
        chown $MY_UID:$MY_GID /app/this-erdiagram.mmd
    depends_on:
      flyway-migrate:
        condition: service_completed_successfully

volumes:
  db-data:
