schema: public
useAllTables: False
selectedTables:
  - doc_unit
  - norms
  - keyword
  - previous_decision
connectionString: postgresql://test:test@localhost:5432/neuris
showDescriptions:
  - columnComments
  - enumValues
