schema: public
useAllTables: False
selectedTables:
  - doc_unit
  - norms
  - keyword
  - previous_decision
connectionString: postgresql://user:pw@localhost:5432/db
showDescriptions:
  - columnComments
  - enumValues
