name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  generate-entity-relationship-model:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate mermaid ER diagram
        run: docker compose up --quiet-pull mermerd
      - name: Upload mermaid diagram
        uses: actions/upload-artifact@v3
        with:
          name: erdiagram
          retention-days: 3
          path: this-erdiagram.mmd

  publish-erdiagram-to-report-repo:
    runs-on: ubuntu-latest
    needs: generate-entity-relationship-model
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lnschroeder/github-pages-playground-reports
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Download mermaid diagram
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
          path: ./entity-relationship-diagrams/
      - name: Check if the erdiagram has changed
        id: erdiagram-change
        run: git diff --quiet --no-index this-erdiagram.mmd latest-erdiagram.mmd
        continue-on-error: true
        working-directory: ./entity-relationship-diagrams/
      - name: Convert .mmd to .svg
        uses: lnschroeder/export-mermaid-erdiagram-action@use-mermerd-binary
        with:
          filename: entity-relationship-diagrams/this-erdiagram
          extractFromDB: false
          convertTo: svg
        if: steps.erdiagram-change.outcome != 'success'
      - name: Push diagram files if the schema has changed
        run: |
          echo "NOW=$(TZ=Europe/Berlin date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV
          git config user.name "GitHubAction"
          git config user.email "<>"
          mv this-erdiagram.mmd latest-erdiagram.mmd
          cp latest-erdiagram.mmd $NOW.mmd
          mv this-erdiagram.svg $NOW.svg
          git add latest-erdiagram.mmd $NOW.mmd $NOW.svg
          git commit -m "${{ github.event.head_commit.message }}" \
            -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" || \
            -m "Live Editor: https://mermaid.live/edit?code=https://raw.githubusercontent.com/${{ github.repository }}-reports/main/entity-relationship-diagrams/$NOW.mmd"
            echo "ER Diagram has not changed"
          git push origin main
        if: steps.erdiagram-change.outcome != 'success'
        working-directory: ./entity-relationship-diagrams/

  build-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - generate-entity-relationship-model
    steps:
      - uses: actions/checkout@v3
      - name: Download ER diagrams
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
          path: _site
      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: _site

  deploy-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-github-pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}