name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  DB_DRIVER: postgresql
  DB_USER: reader
  DB_PASSWORD: NWDMCE5xdipIjRrp
  DB_HOST: hh-pgsql-public.ebi.ac.uk
  DB_PORT: 5432
  DB_DATABASE: pfmegrnargs  

jobs:

  generate-erm-diagrams:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate mermaid ER diagram
        uses: lnschroeder/export-mermaid-erdiagram-action@v1.0.0
        with: 
          config: mermerdConfig.yaml
          output: erdiagram.svg
          connectionString: ${{ env.DB_DRIVER }}://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_DATABASE }}
      - name: Upload .svg
        uses: actions/upload-artifact@v3
        with:
          name: erdiagram
          retention-days: 3
          path: erdiagram.svg
  
  clone-old-erm-diagrams:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lnschroeder/github-pages-playground-reports
      - name: Upload README.md
        uses: actions/upload-artifact@v3
        with:
          name: erdiagram
          retention-days: 3
          path: README.md
          
  build-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - generate-erm-diagrams
    steps:
      - uses: actions/checkout@v3
      - name: Download ER diagrams
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
          path: _site
      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: _site

  deploy-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-github-pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
