name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  REPORT_REPOSITORY: lnschroeder/github-pages-playground-reports

jobs:
  generate-entity-relationship-diagram:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate mermaid ER diagram
        run: docker compose up --quiet-pull mermerd
      - name: Upload mermaid ER diagram
        uses: actions/upload-artifact@v3
        with:
          name: erdiagram
          retention-days: 3
          path: latest-erdiagram.mmd

  publish-entity-relationship-diagram:
    runs-on: ubuntu-latest
    needs: generate-entity-relationship-diagram
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPORT_REPOSITORY }}
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Download mermaid ER diagram
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
          path: ./entity-relationship-diagrams/
#      - name: Check if the ER diagram has changed
#        id: erdiagram-change
#        run: git diff --quiet --no-index latest-erdiagram.mmd latest-erdiagram.mmd
#        continue-on-error: true
#        working-directory: ./entity-relationship-diagrams/
      - name: Check if the ER diagram has changed
        id: erdiagram-check
        run: |
          if git status -s | grep "latest-erdiagram.mmd"; then
            echo "file_changed=true" >> $GITHUB_OUTPUT
          else
            echo "file_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Convert .mmd to .svg
        uses: lnschroeder/export-mermaid-erdiagram-action@use-mermerd-binary
        with:
          filename: entity-relationship-diagrams/latest-erdiagram
          extractFromDB: false
          convertTo: svg
        if: steps.erdiagram-check.file_changed == true'
      - name: Push ER diagram files if the schema has changed
        run: |
          NOW=$(TZ=Europe/Berlin date +'%Y-%m-%dT%H%M%S')
          git config user.name "GitHubAction"
          git config user.email "<>"
          cp latest-erdiagram.mmd $NOW.mmd
          mv latest-erdiagram.svg $NOW.svg
          git add latest-erdiagram.mmd $NOW.mmd $NOW.svg
          git commit -m "${{ github.event.head_commit.message }}" \
            -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" \
            -m "Live Editor: https://mermaid.live/edit?code=https://raw.githubusercontent.com/${{ env.REPORT_REPOSITORY }}/main/entity-relationship-diagrams/$NOW.mmd"
          git push origin main
        if: steps.erdiagram-check.file_changed == true'
        working-directory: ./entity-relationship-diagrams/

  build-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - generate-entity-relationship-diagram
    steps:
      - uses: actions/checkout@v3
      - name: Download ER diagram
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
          path: _site
      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-github-pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}