name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  DB_DRIVER: postgresql
  DB_USER: reader
  DB_PASSWORD: NWDMCE5xdipIjRrp
  DB_HOST: hh-pgsql-public.ebi.ac.uk
  DB_PORT: 5432
  DB_DATABASE: pfmegrnargs  
  
jobs:
  generate-erm-diagrams:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate mermaid ER diagram
        uses: lnschroeder/export-mermaid-erdiagram-action@use-mermerd-binary
        with: 
          extractFromDB: true
          config: mermerdConfig.yaml
          filename: this-erdiagram
          connectionString: ${{ env.DB_DRIVER }}://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_DATABASE }}
      - name: Upload mermaid diagram
        uses: actions/upload-artifact@v3
        with:
          name: erdiagram
          retention-days: 3
          path: this-erdiagram.mmd
          
  push-erdiagram:
    runs-on: ubuntu-latest
    needs: generate-erm-diagrams
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lnschroeder/github-pages-playground-reports
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Set current date as env variable
        run: echo "NOW=$(TZ=Europe/Berlin date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV
      - name: Download new ER diagram
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
      - name: Check if the erdiagram has changed 
        run: git diff --quiet --no-index this-erdiagram.mmd latest-erdiagram.mmd
        continue-on-error: true
      - name: Convert .mmd to .svg
        uses: lnschroeder/export-mermaid-erdiagram-action@use-mermerd-binary
        with: 
          filename: this-erdiagram
          extractFromDB: false
          convertTo: svg
        if: failure()
      - name: Push files if they have changed
        run: |
          git config user.name "GitHubAction"
          git config user.email "<>"
          mv this-erdiagram.mmd latest-erdiagram.mmd
          cp latest-erdiagram.mmd $NOW.mmd
          mv this-erdiagram.svg $NOW.svg
          git add latest-erdiagram.mmd $NOW.mmd $NOW.svg
          git commit -m "${{ github.event.head_commit.message }}" \
            -m "From commit ${{ github.repository }}@${{ github.sha }}" || \ 
            echo "ER Diagram has not changed"
          git push origin main
        if: failure()
    
  clone-old-erm-diagrams:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lnschroeder/github-pages-playground-reports
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Upload README.md
        uses: actions/upload-artifact@v3
        with:
          name: erdiagram
          retention-days: 3
          path: README.md
          
  build-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - generate-erm-diagrams
    steps:
      - uses: actions/checkout@v3
      - name: Download ER diagrams
        uses: actions/download-artifact@v3
        with:
          name: erdiagram
          path: _site
      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: _site

  deploy-github-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-github-pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
