name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  REPORT_REPOSITORY: lnschroeder/github-pages-playground-reports

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.head_commit.message }}
          TEST=${{ github.event.head_commit.message }}
          echo TEST
#  generate-entity-relationship-diagram:
#    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/main' }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Generate mermaid ER diagram
#        run: docker compose up --quiet-pull mermerd
#      - name: Upload mermaid ER diagram
#        uses: actions/upload-artifact@v3
#        with:
#          name: erdiagram
#          retention-days: 3
#          path: latest.mmd
#
#  publish-entity-relationship-diagram:
#    runs-on: ubuntu-latest
#    needs: generate-entity-relationship-diagram
#    if: ${{ github.ref == 'refs/heads/main' }}
#    env:
#      ER_DIAGRAM_PATH: entity-relationship-diagrams
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          repository: ${{ env.REPORT_REPOSITORY }}
#          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
#      - name: Download mermaid ER diagram
#        uses: actions/download-artifact@v3
#        with:
#          name: erdiagram
#          path: ${{ env.ER_DIAGRAM_PATH }}
#      - name: Check if the ER diagram has changed
#        id: erdiagram-check
#        run: |
#          if git status -s | grep latest.mmd; then
#            echo "file_changed=true" >> "$GITHUB_OUTPUT"
#          else
#            echo "file_changed=false" >> $GITHUB_OUTPUT
#          fi
#        working-directory: ${{ env.ER_DIAGRAM_PATH }}
#      - name: Push ER diagram files if the schema has changed
#        run: |
#          NOW=$(TZ=Europe/Berlin date +'%Y-%m-%dT%H%M%S')
#          git config user.name "${{ github.repository }}"
#          git config user.email "<>"
#          cp latest.mmd $NOW.mmd
#          git add latest.mmd $NOW.mmd
#          ESCAPED_COMMIT_MESSAGE=${{ github.event.head_commit.message } | sed 's/"/\\"/g'}
#          git commit \
#            -m $ESCAPED_COMMIT_MESSAGE \
#            -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
#          git push origin main
#          echo "Pushed reports to ${{ github.server_url }}/${{ env.REPORT_REPOSITORY }}" >> $GITHUB_STEP_SUMMARY
#        if: steps.erdiagram-check.outputs.file_changed == 'true'
#        working-directory: ${{ env.ER_DIAGRAM_PATH }}
#
#  build-github-pages:
#    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/main' }}
#    needs:
#      - generate-entity-relationship-diagram
#    steps:
#      - uses: actions/checkout@v3
#      - name: Download ER diagram
#        uses: actions/download-artifact@v3
#        with:
#          name: erdiagram
#          path: _site
#      - name: Upload GitHub Pages
#        uses: actions/upload-pages-artifact@v1
#        with:
#          path: _site
#
#  deploy-github-pages:
#    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/main' }}
#    needs: build-github-pages
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    steps:
#      - name: Deploy GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2
#        env:
#          GITHUB_TOKEN: ${{ github.token }}